//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichmondGrpLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> SchedulePeriod { get; set; }
        public Nullable<int> ScheduleEngineer { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Engineer Engineer { get; set; }
    }
}
